openapi: 3.0.2
info:
  description: |
    Watchman is an HTTP API and Go library to download, parse and offer search functions over numerous trade sanction lists from the United States, European Union governments, agencies, and non profits for complying with regional laws. Also included is a web UI and async webhook notification service to initiate processes on remote systems.
  version: v1
  title: Watchman Admin API
  contact:
    url: https://github.com/moov-io/watchman
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:9094
    description: Local development

tags:
  - name: Admin
    description: Watchman endpoints which are only meant to be exposed for admin dashboards and operations.

paths:
  /version:
    get:
      tags: ["Admin"]
      summary: Get Version
      description: Show the current version of Watchman
      operationId: getVersion
      responses:
        '200':
          description: The current version running
          content:
            text/plain:
              schema:
                type: string
                example: v0.13.1
  /data/refresh:
    post:
      tags: ["Admin"]
      summary: Download and reindex all data sources
      operationId: refreshData
      responses:
        '200':
          description: Data successfully refreshed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DataRefresh"
        '400':
          description: See error message
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/moov-io/base/master/api/common.yaml#/components/schemas/Error'
  /debug/sdn/{sdnId}:
    get:
      tags: ["Admin"]
      summary: Debug SDN
      description: Get an SDN and search index debug information
      operationId: debugSDN
      parameters:
        - name: sdnId
          in: path
          description: SDN ID
          required: true
          schema:
            type: string
            example: 564dd7d1
      responses:
        '200':
          description: SDN with debug information
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DebugSDN"
        '400':
          description: See error message
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/moov-io/base/master/api/common.yaml#/components/schemas/Error'

components:
  schemas:
    SDNDebugMetadata:
      properties:
        indexedName:
          type: string
          description: Exact text stored in our index used for string ranking
          example: mohammad moghisseh
        parsedRemarksId:
          type: string
          description: ID parsed from remarks field
          example: '3603251708570001'
    DebugSDN:
      properties:
        SDN:
          $ref: './client.yaml#/components/schemas/OfacSDN'
        debug:
          $ref: '#/components/schemas/SDNDebugMetadata'
    DataRefresh:
      properties:
        SDNs:
          type: integer
          description: Count of OFAC SDNs after index
          example: 13131
        altNames:
          type: integer
          description: Count of OFAC alternate names after index
          example: 322
        addresses:
          type: integer
          description: Count of OFAC Addresses after index
          example: 4155
        sectoralSanctions:
          type: integer
          description: Count of SSI entities after index
          example: 667
        deniedPersons:
          type: integer
          description: Count of BSL denied persons after index
          example: 5889
        bisEntities:
          type: integer
          description: Count of BIS entities after index
          example: 6831
        timestamp:
          type: string
          format: date-time
          example: 2006-01-02T15:04:05Z07:00
