---
version: "2"

services:
  web:
    restart: always
    build: .
    ports:
      - 8081:8081

  nginx:
    restart: always
    build: ./nginx
    container_name: nginx
    ports:
      - "8443:8443"
    depends_on:
      - web
