name: Merge Repositories into Subdirectories
on:
  workflow_dispatch: # Manually trigger the workflow
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      # Checkout the target repository (e.g., morphic)
      - name: Checkout morphic
        uses: actions/checkout@v3
        with:
          repository: srvo/morphic
          path: morphic
          fetch-depth: 0 # Full clone

      # Checkout trafilatura and copy its files into a subdirectory
      - name: Checkout trafilatura
        uses: actions/checkout@v3
        with:
          repository: srvo/trafilatura
          path: trafilatura
          fetch-depth: 0 # Full clone

      - name: Copy trafilatura into morphic/trafilatura
        run: |
          mkdir -p morphic/trafilatura
          cp -r trafilatura/* morphic/trafilatura/

      # Checkout maigret and copy its files into a subdirectory
      - name: Checkout maigret
        uses: actions/checkout@v3
        with:
          repository: srvo/maigret
          path: maigret
          fetch-depth: 0 # Full clone

      - name: Copy maigret into morphic/maigret
        run: |
          mkdir -p morphic/maigret
          cp -r maigret/* morphic/maigret/

      # Checkout watchman and copy its files into a subdirectory
      - name: Checkout watchman
        uses: actions/checkout@v3
        with:
          repository: srvo/watchman
          path: watchman
          fetch-depth: 0 # Full clone

      - name: Copy watchman into morphic/watchman
        run: |
          mkdir -p morphic/watchman
          cp -r watchman/* morphic/watchman/

      # Checkout physrisk-api and copy its files into a subdirectory
      - name: Checkout physrisk-api
        uses: actions/checkout@v3
        with:
          repository: srvo/physrisk-api
          path: physrisk-api
          fetch-depth: 0 # Full clone

      - name: Copy physrisk-api into morphic/physrisk-api
        run: |
          mkdir -p morphic/physrisk-api
          cp -r physrisk-api/* morphic/physrisk-api/

      # Checkout metaforecast and copy its files into a subdirectory
      - name: Checkout metaforecast
        uses: actions/checkout@v3
        with:
          repository: srvo/metaforecast
          path: metaforecast
          fetch-depth: 0 # Full clone

      - name: Copy metaforecast into morphic/metaforecast
        run: |
          mkdir -p morphic/metaforecast
          cp -r metaforecast/* morphic/metaforecast/

      # Commit and push the changes to morphic
      - name: Commit and push changes to morphic
        run: |
          cd morphic
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Merged repositories into subdirectories"
          git push origin main
